### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by maciekish** [jdahlblom/SMSTerminal#5]
Vad hände med ditt Discord-konto? Försökte få tag i dig häromdan men det står Deleted User.

**Comment by jdahlblom** [comment]
Jag  har nytt konto, skickade friend request 2 ggr men du visste säkert inte vem det var. Skickar igen!

**Comment by jdahlblom** [comment]
Ingen request?

**Comment by jdahlblom** [comment]
Fick du ingen request?
